private_data:
  log_input: false
  log_output: false
setting_type: default
set_all:
  file: 10
  console: 10
data_types:
  file: 10
  console: 10
prepper:
  file: 10
  console: 10
cascade:
  file: 10
  console: 10
sanitiser:
  file: 10
  console: 10
validators:
  file: 10
  console: 10
llm_handler:
  file: 10
  console: 10
cache:
  file: 10
  console: 10
workflows:
  file: 10
  console: 10
strings:
  file: 10
  console: 10
time:
  file: 10
  console: 10
file_importers:
  file: 10
  console: 10
unhandled_errors:
  file: 10
  console: 10
