version: 2

build:
  # Leaving as default
  os: ubuntu-20.04
  tools:
    python: "3.12"
  # Setting things up so poetry is used
  # thus requirements.txt is not needed
  jobs:
    post_create_environment:
      # Install poetry
      - pip install poetry
      # Tell poetry to not use a virtual environment
      - poetry config virtualenvs.create false
    post_install:
      # Install dependencies from the docs group
      - poetry install --with docs

sphinx:
  configuration: docs/conf.py